# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_path', models.CharField(db_index=True, max_length=255)),
                ('new_path', models.CharField(blank=True, max_length=255)),
                ('regex', models.BooleanField(default=False)),
                ('permanent', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-priority'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='redirect',
            unique_together=set([('old_path', 'new_path')]),
        ),
    ]
